# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `filesize` gem.
# Please instead update this file by running `bin/tapioca gem filesize`.

class Filesize
  include ::Comparable

  # @param size [Number] A file size, in bytes.
  # @param type [SI, BINARY] Which type to use for conversions.
  # @return [Filesize] a new instance of Filesize
  def initialize(size, type = T.unsafe(nil)); end

  # @return [Filesize]
  def *(other); end

  # @return [Filesize]
  def +(other); end

  # @return [Filesize]
  def -(other); end

  # @return [Filesize]
  def /(other); end

  def <=>(other); end

  # @api private
  # @return [Array<self, other>]
  def coerce(other); end

  # Same as {#to_s} but with an automatic determination of the most
  # sensible unit.
  #
  # @return [String]
  # @see #to_s
  def pretty(args = T.unsafe(nil)); end

  # @param unit [String] Which unit to convert to.
  # @return [Float] Returns the size in a given unit.
  def to(unit = T.unsafe(nil)); end

  # @param unit [String] Which unit to convert to.
  # @return [Float] Returns the size in a given unit.
  def to_f(unit = T.unsafe(nil)); end

  # @return [Number] Returns the size in bytes.
  def to_i; end

  # @return [Number] Returns the size in bytes.
  def to_int; end

  # @param unit [String] Which unit to convert to.
  # @return [String] Same as {#to_f}, but as a string, with the unit appended.
  # @see #to_f
  def to_s(unit = T.unsafe(nil), args = T.unsafe(nil)); end

  class << self
    # Parses a string, which describes a file size, and returns a
    # Filesize object.
    #
    # @param arg [String] A file size to parse.
    # @raise [ArgumentError] Raised if the file size cannot be parsed properly.
    # @return [Filesize]
    def from(arg); end

    # @api private
    # @return [Hash<:prefix, :size, :type>]
    def parse(string); end
  end
end

# Set of rules describing file sizes according to binary units.
Filesize::BINARY = T.let(T.unsafe(nil), Hash)

# The size of a CD
Filesize::CD = T.let(T.unsafe(nil), Filesize)

# The same as a DVD 5
Filesize::DVD = T.let(T.unsafe(nil), Filesize)

# The size of a double-sided single-layer DVD
Filesize::DVD_10 = T.let(T.unsafe(nil), Filesize)

# The size of a double-sided DVD, combining a DVD-9 and a DVD-5
Filesize::DVD_14 = T.let(T.unsafe(nil), Filesize)

# The size of a double-sided dual-layer DVD
Filesize::DVD_18 = T.let(T.unsafe(nil), Filesize)

# The size of a common DVD
Filesize::DVD_5 = T.let(T.unsafe(nil), Filesize)

# The size of a single-sided dual-layer DVD
Filesize::DVD_9 = T.let(T.unsafe(nil), Filesize)

# The size of a floppy disk
Filesize::Floppy = T.let(T.unsafe(nil), Filesize)

# Set default precision
Filesize::PRECISION = T.let(T.unsafe(nil), Integer)

# @deprecated Please use TYPE_PREFIXES[:SI] instead
Filesize::PREFIXES = T.let(T.unsafe(nil), Array)

# Set of rules describing file sizes according to SI units.
Filesize::SI = T.let(T.unsafe(nil), Hash)

Filesize::TYPE_PREFIXES = T.let(T.unsafe(nil), Hash)

# The size of a Zip disk
Filesize::ZIP = T.let(T.unsafe(nil), Filesize)
