# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `interactive_editor` gem.
# Please instead update this file by running `bin/tapioca gem interactive_editor`.

class InteractiveEditor
  # @return [InteractiveEditor] a new instance of InteractiveEditor
  def initialize(editor); end

  def edit(object, file = T.unsafe(nil)); end

  # Returns the value of attribute editor.
  def editor; end

  # Sets the attribute editor
  #
  # @param value the value to set the attribute editor to.
  def editor=(_arg0); end

  def execute; end

  class << self
    def edit(editor, self_, file = T.unsafe(nil)); end
    def find_editor; end
  end
end

InteractiveEditor::EDITORS = T.let(T.unsafe(nil), Hash)

module InteractiveEditor::Editors
  def ed(*args); end
  def emacs(*args); end
  def mate(*args); end
  def mvim(*args); end
  def nano(*args); end
  def nvim(*args); end
  def subl(*args); end
  def vi(*args); end
  def vim(*args); end
end

module InteractiveEditor::Exec
  extend ::InteractiveEditor::Exec::MRI
end

module InteractiveEditor::Exec::Java
  def system(file, *args); end
end

module InteractiveEditor::Exec::MRI
  def system(file, *args); end
end

InteractiveEditor::VERSION = T.let(T.unsafe(nil), String)
