# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `rails_heroicon` gem.
# Please instead update this file by running `bin/tapioca gem rails_heroicon`.

module RailsHeroicon; end

module RailsHeroicon::Helper
  # To add a heroicon, call <tt><%= heroicon "icon_name" %></tt> on your erb template.
  # Head over to https://heroicons.com to view all the icons.
  #
  # == Options
  # The helper method accepts mutiple arguments such as:
  #
  # === Variant
  # There are two types of variants: 'outline' and 'solid', the default being the 'outline'.
  # To specify the solid variant, call <tt><%= heroicon "icon_name", variant: "solid" %></tt>
  #
  # === HTML attributes
  # Any <tt>html</tt> attribute is supported, for eg:
  #
  # <tt><%= heroicon "icon_name", class: "text-gray-500", data: { controller: "icon" } %></tt>
  #
  # === Handling the icon size
  # Normally, if you're just using vanilla heroicons with tailwindcss, you'd set <tt>w-5 h-5</tt> as class attributes
  # on the svg. With this helper, you just need to set the <tt>size</tt> attribute on the icon.
  #
  # <tt><%= heroicon "icon_name", size: 20 %></tt>
  #
  # This will set the <tt>height</tt> and <tt>width</tt> attribute on the svg.
  #
  # If the variant is set as <tt>outline</tt>, size automatically defaults to 24, and if the variant is set as
  # <tt>solid</tt>, size automatically defaults to 20. However, this can be over-written with the <tt>size</tt>
  # attribute.
  #
  # == Accessibility
  # The helper method automatically sets <tt>aria-hidden=true</tt> if <tt>aria-label</tt> is not set, and
  # if <tt>aria-label</tt> is set, then <tt>role=img</tt> is set automatically.
  def heroicon(symbol, title: T.unsafe(nil), **options); end
end

RailsHeroicon::ICONS = T.let(T.unsafe(nil), Hash)
RailsHeroicon::ICON_PATH = T.let(T.unsafe(nil), String)

class RailsHeroicon::RailsHeroicon
  # @raise [UndefinedVariant]
  # @return [RailsHeroicon] a new instance of RailsHeroicon
  def initialize(icon, variant: T.unsafe(nil), size: T.unsafe(nil), **options); end

  # Returns the value of attribute options.
  def options; end

  # Finds the svg icon with respect to variant.
  #
  # @raise [UndefinedIcon]
  def svg_path; end

  private

  def a11y; end

  # If the user has explicitly stated the size attribute, then use that. If size attribute is not passed
  # then default to 24 if variant is outline, else default to 20 if variant is solid.
  def icon_size_with(size); end

  # @return [Boolean]
  def outline?; end

  # @return [Boolean]
  def solid?; end
end

RailsHeroicon::RailsHeroicon::VARIANTS = T.let(T.unsafe(nil), Array)
class RailsHeroicon::Railtie < ::Rails::Railtie; end

class RailsHeroicon::UndefinedIcon < ::StandardError
  # @return [UndefinedIcon] a new instance of UndefinedIcon
  def initialize(icon = T.unsafe(nil), exception_type = T.unsafe(nil)); end
end

class RailsHeroicon::UndefinedVariant < ::StandardError
  # @return [UndefinedVariant] a new instance of UndefinedVariant
  def initialize(msg = T.unsafe(nil), exception_type = T.unsafe(nil)); end
end

RailsHeroicon::VERSION = T.let(T.unsafe(nil), String)
