# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `stackprof` gem.
# Please instead update this file by running `bin/tapioca gem stackprof`.

module StackProf
  class << self
    def results(*_arg0); end
    def run(*_arg0); end
    def running?; end
    def sample; end
    def start(*_arg0); end
    def stop; end
  end
end

class StackProf::Middleware
  # @return [Middleware] a new instance of Middleware
  def initialize(app, options = T.unsafe(nil)); end

  def call(env); end

  class << self
    # Returns the value of attribute enabled.
    def enabled; end

    # Sets the attribute enabled
    #
    # @param value the value to set the attribute enabled to.
    def enabled=(_arg0); end

    # @return [Boolean]
    def enabled?(env); end

    # Returns the value of attribute interval.
    def interval; end

    # Sets the attribute interval
    #
    # @param value the value to set the attribute interval to.
    def interval=(_arg0); end

    # Returns the value of attribute metadata.
    def metadata; end

    # Sets the attribute metadata
    #
    # @param value the value to set the attribute metadata to.
    def metadata=(_arg0); end

    # Returns the value of attribute mode.
    def mode; end

    # Sets the attribute mode
    #
    # @param value the value to set the attribute mode to.
    def mode=(_arg0); end

    # Returns the value of attribute path.
    def path; end

    # Sets the attribute path
    #
    # @param value the value to set the attribute path to.
    def path=(_arg0); end

    # Returns the value of attribute raw.
    def raw; end

    # Sets the attribute raw
    #
    # @param value the value to set the attribute raw to.
    def raw=(_arg0); end

    def save; end
  end
end

class StackProf::Report
  # @return [Report] a new instance of Report
  def initialize(data); end

  # @raise [ArgumentError]
  def +(other); end

  def add_lines(a, b); end
  def convert_to_d3_flame_graph_format(name, stacks, depth); end

  # Returns the value of attribute data.
  def data; end

  def files; end
  def flamegraph_row(f, x, y, weight, addr); end
  def flamegraph_stacks(raw); end
  def frames(sort_by_total = T.unsafe(nil)); end
  def max_samples; end
  def modeline; end
  def normalized_frames; end
  def overall_samples; end
  def print_alphabetical_flamegraph(f = T.unsafe(nil), skip_common = T.unsafe(nil)); end
  def print_callgrind(f = T.unsafe(nil)); end
  def print_d3_flamegraph(f = T.unsafe(nil), skip_common = T.unsafe(nil)); end
  def print_debug; end
  def print_dump(f = T.unsafe(nil)); end
  def print_file(filter, f = T.unsafe(nil)); end
  def print_files(sort_by_total = T.unsafe(nil), limit = T.unsafe(nil), f = T.unsafe(nil)); end
  def print_flamegraph(f, skip_common, alphabetical = T.unsafe(nil)); end
  def print_graphviz(options = T.unsafe(nil), f = T.unsafe(nil)); end
  def print_json(f = T.unsafe(nil)); end
  def print_method(name, f = T.unsafe(nil)); end
  def print_stackcollapse; end
  def print_text(sort_by_total = T.unsafe(nil), limit = T.unsafe(nil), select_files = T.unsafe(nil), reject_files = T.unsafe(nil), select_names = T.unsafe(nil), reject_names = T.unsafe(nil), f = T.unsafe(nil)); end
  def print_timeline_flamegraph(f = T.unsafe(nil), skip_common = T.unsafe(nil)); end
  def version; end

  # Walk up and down the stack from a given starting point (name).  Loops
  # until `:exit` is selected
  def walk_method(name); end

  private

  def callers_for(addr); end
  def root_frames; end
  def source_display(f, file, lines, range = T.unsafe(nil)); end
end

StackProf::VERSION = T.let(T.unsafe(nil), String)
